---
apiVersion: batch/v1
kind: Job
metadata:
  name: hellojob
spec:
  backoffLimit: 5
  template:           
    metadata:
      name: job
    spec:
      restartPolicy: OnFailure                  
      containers:
        - name: job
          image: alpine
          command:
            - sleep
            - 5s 