---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed
---  
apiVersion: v1
kind: StatefulSet
metadata:
  name: stateful
  labels:
    app:nginx
spec:
  minReadySeconds: 1
  replicas: 3
  ServiceName: nginx-svc
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
              target: 80  
      volumeMounts:
        name: stateful-nginx
        mountPath: /usr/share/nginx/html  
      volumes:
        - name: mysql-pvol
         persistentVolumeClaim:
           claimName: mysql-pvc