---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vinod-rs
spec:
  minReadySeconds: 1
  replicas: 5
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
      containers:
        - name: vinod-rs
          image: jenkins/jenkins:lts-jdk11
          ports:
            - containerPort: 8080
        - name: vinod-
          image: alpine:3
          args:
            - sleep
            - 1d  
