---
apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  labels:
    app: httpd
spec:
  ports:
    - name: httpd-svc
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: httpd
  type: LoadBalancer
---  
  apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    name: httpd
    labels:
      app: httpd
  spec:
    minReadySeconds: 1
    replicas: 3
    selector:
      matchLabels:
        app: httpd
    template:
      metadata:
        name: httpd
        labels:
          app: httpd         
      spec:
        containers:
          - name: httpd
            image: httpd:2.4.57
            ports:
              - name: http
                containerPort: 80
            livenessProbe:
              failureThreshold: 1
              initialDelaySeconds: 1
              periodSeconds: 1
              successThreshold: 1
              timeoutSeconds: 10
              exec:
                command:
                  - sleep
                  - 10s
            readinessProbe:
              failureThreshold: 3
              initialDelaySeconds: 2
              successThreshold: 2
              periodSeconds: 2
              timeoutSeconds: 1
              exec:
                command:
                  - sleep
                  - 10s                     




