---
apiVersion: v1
kind: Pod
metadata: 
  name: exec3
spec:
  containers:
    - name: gun
      image: nginx
      ports:
        - name: nginx
          containerPort: 80
    - name: httpd
      image: httpd
      ports:
        - name: httpd
          containerport: 80