---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: '* * * * *'
  jobTemplate:
    metadata:
      name: cronjob
    spec:
      backoffLimit: 2
      template:
        metadata:
          name: cronjob
        spec:
          restartPolicy: OnFailure  
          containers:
            - name: cronjob
              image: alpine
              args:
                - sleep
                - 3s 