apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginxdeamon
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: deamon
          # ports:
          #   containerPort: 80      