---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-rs
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels:
      app: jenkins  
  template:
    metadata:
      name: replica
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:its-jdk11
          name: replica
          ports:
            - containerPort: 8080
        - image: alpine:3
          name: vinod
          args:
            - sleep
            - 1d    