---
apiVersion: v1
kind: Pod
metadata:
  name: restartfailure  ##Never
spec:
  restartPolicy: OnFailure  ##Never
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 3sm  ##1d

### using above manifest we can use Onfailure,restartAlways,RestartNever....       