---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  labels:
    app:nginx
spec:
  ports:
    - name: nginx
      port: 80
  clusterIP: None
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: statefulset
spec:
  replicas: 2
  minReadySeconds: 1
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx    
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
              name: nginx
              protocol: TCP
          volumeMounts:
            - name: stateful-nginx
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: nginx-state
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi 
