---
apiVersion: v1
kind: Pod
metadata:
  name: exec2
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - name: nginx
          containerPort: 80
    - image: alpine
      name: alpine
      args:
        - sleep
        - 1d      