- name: installing http                                           
  become: yes
  tasks:
    - name: update packages and install httpd
      ansible.builtin.apt:
        name: httpd
        state: present
    - name: enable and start apache
      ansible.builtin.systemd:
        name: httpd
        enabled: yes
        state: started
    - name: install apache server
      ansible.builtin.apt:
        name: php
        state: present
    - name: copy the info.php file
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
    - name: restart apache
      ansible.builtin.systemd:
        name: httpd
        state: restarted
          
        
          

          


