apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
spec:
  containers:
    - image: mysql:8
      name: mysqldb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'rootroot'
        - name: MYSQL_DATABASE
          value: 'mysqldb'
        - name: MYSQL_USER
          value: 'devops'
        - name: MYSQL_PASSWORD
          value: 'rootroot ' 
      ports:
        - containerPort: 3306
          protocol: TCP
          name: mysql
                  
  