apiVersion: apps/v1 
kind: Deployment
metadata:
  name: petclinc
spec:
  minReadySeconds: 1
  replicas: 5
  selector:
    matchLabels:
      app: petclinc
  template:
    metadata:
      labels:
        name: petclinc
        app: petclinc
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: qt1234.jfrog.io/workshop-docker-local/petclinic:latest
          name: petclinc
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "250m"  

                
