---
- name: install lamp server on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: update packages and install apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    - name: install php packages
      ansible.builtin.apt:
        name: 
          - php
          - libapache2-mod-php
          - php-mysql
        state: present  
    - name: copy info.php page
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
    - name: restart apache2
      ansible.builtin.systemd:
        name: apache2
        state: restarted

---
- name: install lamp stack
  hosts: all
  become: yes
  tasks:
    - name: update packages and install httpd
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: install php
      ansible.builtin.yum:
        name: php
        stste: present
    - name: restart httpd
      ansible.builtin.systemd:
        name: httpd
        state: restarted            


            
